// src/pages/PrivacyPolicy.jsx
import React from 'react';
import Breadcrumbs from '../components/Breadcrumbs';
import { ShieldAlert, Scale, Eye, BookOpen } from 'lucide-react';

export default function PrivacyPolicy() {
  return (
    <div className="font-sans text-slate-100 bg-slate-950">
      <Breadcrumbs />

      {/* Header section */}
      <section className="relative bg-slate-900 py-16 px-4 text-center">
        <div className="max-w-4xl mx-auto space-y-3">
          <span className="text-orange-500 text-xs font-bold uppercase tracking-widest">Legal Information</span>
          <h1 className="text-3xl md:text-5xl font-black text-white leading-tight">Privacy Policy &amp; Terms</h1>
          <p className="text-slate-400 text-sm md:text-base max-w-2xl mx-auto">
            Review legal disclosures, terms of service conditions, accessibility declarations, and placeholder verification notices.
          </p>
        </div>
      </section>

      {/* Main text content body */}
      <section className="py-16 px-4 max-w-4xl mx-auto text-left">
        <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 md:p-10 shadow-xl space-y-12">

          {/* Important License & Certification Verification Box */}
          <div className="bg-orange-500/10 border border-orange-500/20 p-6 rounded-2xl space-y-3">
            <h3 className="text-orange-500 text-base font-bold uppercase tracking-wider flex items-center gap-2">
              <ShieldAlert className="w-5 h-5 shrink-0 animate-pulse" />
              Required Professional Disclaimer Notice
            </h3>
            <p className="text-slate-300 text-xs md:text-sm leading-relaxed">
              Summit Build Contractors is a mock demonstration website created to showcase front-end web design and engineering capabilities. All business licenses, structural certifications, warranties coverage terms, financing approval claims, trade associations, and customer reviews presented on this website are placeholder materials.
            </p>
            <p className="text-slate-300 text-xs md:text-sm leading-relaxed">
              These details must be thoroughly reviewed, verified, and replaced with actual company documentation, certification numbers, and legal policy texts prior to deploying this website as an active corporate business channel.
            </p>
          </div>

          {/* Section 1: Privacy Policy */}
          <div className="space-y-4">
            <h2 id="privacy" className="text-white text-xl md:text-2xl font-extrabold flex items-center gap-2.5 border-b border-slate-800 pb-2">
              <Eye className="w-5 h-5 text-orange-500 shrink-0" />
              1. Web Privacy Policy
            </h2>
            <p className="text-slate-400 text-xs leading-relaxed">
              Last updated: July 15, 2026. At Summit Build Contractors, we respect your privacy. This policy governs how we collect and process information through our website contact forms, estimate calculators, and mock chatbot applications.
            </p>
            <p className="text-slate-400 text-xs leading-relaxed">
              <strong>Personal Data Collection:</strong> We collect your full name, email, phone number, and street addresses only when you submit them voluntarily through our site forms. This data is processed securely to generate mock project records.
            </p>
            <p className="text-slate-400 text-xs leading-relaxed">
              <strong>Cookies &amp; Tracking:</strong> We use basic browser session cookies and local storage tokens to optimize form completions and maintain your ongoing mock chatbot session. We do not transmit tracking metrics to third-party ad providers.
            </p>
          </div>

          {/* Section 2: Terms and Conditions */}
          <div className="space-y-4">
            <h2 id="terms" className="text-white text-xl md:text-2xl font-extrabold flex items-center gap-2.5 border-b border-slate-800 pb-2">
              <Scale className="w-5 h-5 text-orange-500 shrink-0" />
              2. Terms &amp; Conditions
            </h2>
            <p className="text-slate-400 text-xs leading-relaxed">
              By accessing, browsing, or submitting details on the Summit Build Contractors website, you agree to these Terms and Conditions in full.
            </p>
            <p className="text-slate-400 text-xs leading-relaxed">
              <strong>Estimates and Pricing Exclusions:</strong> Any estimated budgets, timeline projections, and project duration examples generated by our interactive forms, pages, or chat widgets are illustrative estimates. They do not constitute a legally binding service contract or guaranteed pricing. Full physical inspections and formal contracts signed by both parties are required to secure standard pricing models.
            </p>
            <p className="text-slate-400 text-xs leading-relaxed">
              <strong>Intellectual Property:</strong> All reusable layout elements, code components, dynamic structured schemas, and textual copying are owned by Summit Build Contractors. No content may be scraped or copied for competing commercial directories.
            </p>
          </div>

          {/* Section 3: Accessibility Statement */}
          <div className="space-y-4">
            <h2 id="accessibility" className="text-white text-xl md:text-2xl font-extrabold flex items-center gap-2.5 border-b border-slate-800 pb-2">
              <BookOpen className="w-5 h-5 text-orange-500 shrink-0" />
              3. Accessibility Statement
            </h2>
            <p className="text-slate-400 text-xs leading-relaxed">
              We are committed to providing a digitally accessible web environment for individuals with disabilities. We strive to maintain compliance with WCAG 2.1 Level AA accessibility standards.
            </p>
            <p className="text-slate-400 text-xs leading-relaxed">
              Our site includes semantic HTML layout structures, focus indicators for keyboard-only navigation users, ARIA roles, descriptive image alt text, high-contrast button styling, and customizable reduced-motion styling indicators. If you encounter any digital accessibility barriers on our site, please contact us immediately so we can remediate them.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
